name: Daily Bitcoin Treasury Scraping

on:
  schedule:
    - cron: '0 0 * * *'  # Run at 00:00 UTC every day
  workflow_dispatch:  # Allow manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # Using 3.11 for better compatibility
        
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium
        
    - name: Run scraper
      run: |
        python treasury_scraper.py
        
    - name: Commit and push if changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add category_btc-treasuries.csv
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update Bitcoin Treasury data [skip ci]" && git push) 